### ISSUE TITLE
Runtime error when trying to run the beautifuldiscord line code

### ISSUE THREAD

**Issue by RjGunner111** [beautiful-discord-community/resources#61]
https://gyazo.com/6c48669e9331ff32cadf869838b89368 as i type in (as the usual when using beautifuldiscord) "python -m beautifuldiscord" gives me this error. if there is a solution to this, please reply to this message.

**Comment by jakeoid** [comment]
This is the incorrect place for reporting issues related to BeautifuDiscord itself and not the themes. Please refer to [leovoel/BeautifulDiscord](https://github.com/leovoel/BeautifulDiscord).
